name: CI-CD backend

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "back/**"
      - ".github/workflows/backend.yml"

jobs:
  tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests and generate Jacoco report
        run: mvn clean test jacoco:report

      - name: Upload backend test results
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: back/target/site/jacoco
          retention-days: 1

  code-quality-analysis:
    needs: tests
    name: Frontend Code Quality Analysis with SonarCloud
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Run tests and generate Jacoco report
        run: mvn clean test jacoco:report

      - name: SonarCloud Scan
        run: mvn verify sonar:sonar -Dsonar.projectKey=openclassroomseyka_gerez-un-projet-collaboratif-en-int-grant-une-demarche-ci-cd-backend -Dsonar.organization=openclassroomseyka -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN_BACK }}
